# .github/ISSUE_TEMPLATE/config.yml
blank_issues_enabled: false
contact_links:
  - name: Security Issues
    url: https://github.com/tonydail/development-container-utilities/security/advisories
    about: Please report security vulnerabilities here.
