name: Enhancement Request
description: Suggest an improvement or new feature for the project.
labels: ["enhancement", "feature", "triage"]
projects: ["Dev containers"]
assignees:
  - ''

body:
  - type: markdown
    attributes:
      value: "### Thanks for suggesting an enhancement! Please provide the following details."
  
  - type: dropdown
    id: enhancement-type
    attributes:
      label: "Enhancement Type"
      description: "What type of enhancement is this?"
      options:
        - New Feature
        - Improvement to Existing Feature
        - Performance Enhancement
        - Documentation Enhancement
        - Developer Experience Improvement
        - Security Enhancement
    validations:
      required: true
  
  - type: textarea
    id: problem-statement
    attributes:
      label: "Problem Statement"
      description: "Is your enhancement request related to a problem? Please describe."
      placeholder: "I'm always frustrated when... / It would be helpful if..."
    validations:
      required: true
  
  - type: textarea
    id: solution-description
    attributes:
      label: "Proposed Solution"
      description: "A clear and concise description of what you want to happen."
      placeholder: "Describe your proposed solution here..."
    validations:
      required: true
  
  - type: textarea
    id: alternatives
    attributes:
      label: "Alternative Solutions"
      description: "Describe any alternative solutions or features you've considered."
      placeholder: "Alternative approaches could include..."
    validations:
      required: false
  
  - type: textarea
    id: use-cases
    attributes:
      label: "Use Cases"
      description: "Describe specific use cases or scenarios where this enhancement would be beneficial."
      placeholder: |
        1. When developing with...
        2. During container setup...
        3. While debugging...
    validations:
      required: true
  
  - type: dropdown
    id: priority
    attributes:
      label: "Priority Level"
      description: "How important is this enhancement to you?"
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Significantly impacts productivity
        - Critical - Blocking current work
    validations:
      required: true
  
  - type: checkboxes
    id: impact-areas
    attributes:
      label: "Impact Areas"
      description: "Which areas of the project would this enhancement affect?"
      options:
        - label: "Dev container scripts"
        - label: "Docker configuration"
        - label: "Development environment setup"
        - label: "Documentation"
        - label: "Testing/CI"
        - label: "Performance"
        - label: "Security"
        - label: "User experience"
  
  - type: textarea
    id: technical-details
    attributes:
      label: "Technical Implementation Details"
      description: "If you have ideas about how this could be implemented, please share them."
      placeholder: "This could be implemented by..."
    validations:
      required: false
  
  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context"
      description: "Add any other context, screenshots, mockups, or examples about the enhancement request here."
    validations:
      required: false
  
  - type: checkboxes
    id: contribution
    attributes:
      label: "Contribution"
      description: "Are you willing to contribute to this enhancement?"
      options:
        - label: "I would like to work on this enhancement"
        - label: "I can provide additional requirements/feedback"
        - label: "I can help with testing"
        - label: "I can help with documentation"